# Generated by Django 5.2.8 on 2025-11-21 12:17

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=store.models.get_file_path)),
                ('description', models.TextField(max_length=75)),
                ('status', models.BooleanField(default=False, help_text='0=default,1-Hidden')),
                ('trending', models.CharField(max_length=20)),
                ('meta_title', models.CharField(max_length=10)),
                ('meta_keyword', models.CharField(max_length=15)),
                ('meta_description', models.TextField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
