# Generated by Django 5.2.8 on 2025-11-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=375),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(max_length=320),
        ),
    ]
