# Generated by Django 5.2.8 on 2025-11-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productitem_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='small_description',
            field=models.TextField(max_length=275),
        ),
    ]
