# Generated by Django 5.2.8 on 2025-11-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productitem_small_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.TextField(max_length=2150),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='small_description',
            field=models.TextField(max_length=575),
        ),
    ]
