# Generated by Django 5.2.8 on 2025-12-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_product_id_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='meta_description',
            field=models.TextField(max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='meta_keyword',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='meta_title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
